### ISSUE TITLE
GitHub actions should notify on failure

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1068]
When the GitHub actions fails to build for either Android or iOS a message should be posted to the internal RocketChat channel.

**Comment by jleach** [comment]
Something like this should work. I added the token to our repo. This will publish to the #test channel for now until everything works as expected. Then we can point it to our team channel.

```
- name: My cool step
   env:
      - ROCKETCHAT_WEBHOOK: ${{ secrets. ROCKETCHAT_WEBHOOK }}
   run: |
       curl -X POST -H 'Content-Type: application/json' --data '{"alias":"Rocket","text":"BC Wallet build 10181 failed.","attachments":[{"title":"Run Status","title_link":"https://github.com/hyperledger/aries-mobile-agent-react-native/actions/runs/5204563775","text":"Build 12344 failed","color":"#764FA5"}]}' ${ROCKETCHAT_WEBHOOK}
```
