### ISSUE TITLE
intermittently getting "The link is not valid" during get person credential flow

### ISSUE THREAD

**Issue by cvarjao** [bcgov/bc-wallet-mobile#983]
Error:
![Screenshot](https://user-images.githubusercontent.com/1348549/226397184-62554b12-2af2-4e23-99cc-2f07d5006ac0.png)

Device: iPhone 11 (iOS 16.1), Samsung S21

**Comment by marcos-carretero** [comment]
This issue has been logged in IDIM JIRA as IASP-15079 for the IAS team to investigate and remediate.

**Comment by WadeBarnes** [comment]
@marcos-carretero, Let me know if you need me to adjust the resources on the agent at all.

**Comment by WadeBarnes** [comment]
The resources (CPU allocation) on the agent are rather low based on the throttling issues we've been investigating recently.  It could be impacting issuing performance.
```
- resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
```
